// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample_gps.proto

package com.chedaojunan.report.model;

public final class FrequencyGpsData {
  private FrequencyGpsData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FrequencyGpsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FrequencyGps)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string deviceId = 1;</code>
     */
    String getDeviceId();
    /**
     * <code>string deviceId = 1;</code>
     */
    com.google.protobuf.ByteString
    getDeviceIdBytes();

    /**
     * <code>string deviceImei = 2;</code>
     */
    String getDeviceImei();
    /**
     * <code>string deviceImei = 2;</code>
     */
    com.google.protobuf.ByteString
    getDeviceImeiBytes();

    /**
     * <code>string localTime = 3;</code>
     */
    String getLocalTime();
    /**
     * <code>string localTime = 3;</code>
     */
    com.google.protobuf.ByteString
    getLocalTimeBytes();

    /**
     * <code>string tripId = 4;</code>
     */
    String getTripId();
    /**
     * <code>string tripId = 4;</code>
     */
    com.google.protobuf.ByteString
    getTripIdBytes();

    /**
     * <code>string serverTime = 5;</code>
     */
    String getServerTime();
    /**
     * <code>string serverTime = 5;</code>
     */
    com.google.protobuf.ByteString
    getServerTimeBytes();

    /**
     * <code>double lat = 6;</code>
     */
    double getLat();

    /**
     * <code>double longi = 7;</code>
     */
    double getLongi();

    /**
     * <code>double alt = 8;</code>
     */
    double getAlt();

    /**
     * <code>double dir = 9;</code>
     */
    double getDir();

    /**
     * <code>double gpsSpeed = 10;</code>
     */
    double getGpsSpeed();
  }
  /**
   * Protobuf type {@code FrequencyGps}
   */
  public  static final class FrequencyGps extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FrequencyGps)
      FrequencyGpsOrBuilder {
    private static final long serialVersionUID = 0L;
    // Use FrequencyGps.newBuilder() to construct.
    private FrequencyGps(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FrequencyGps() {
      deviceId_ = "";
      deviceImei_ = "";
      localTime_ = "";
      tripId_ = "";
      serverTime_ = "";
      lat_ = 0D;
      longi_ = 0D;
      alt_ = 0D;
      dir_ = 0D;
      gpsSpeed_ = 0D;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FrequencyGps(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              deviceId_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              deviceImei_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              localTime_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              tripId_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              serverTime_ = s;
              break;
            }
            case 49: {

              lat_ = input.readDouble();
              break;
            }
            case 57: {

              longi_ = input.readDouble();
              break;
            }
            case 65: {

              alt_ = input.readDouble();
              break;
            }
            case 73: {

              dir_ = input.readDouble();
              break;
            }
            case 81: {

              gpsSpeed_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
      return FrequencyGpsData.internal_static_FrequencyGps_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
      return FrequencyGpsData.internal_static_FrequencyGps_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              FrequencyGps.class, Builder.class);
    }

    public static final int DEVICEID_FIELD_NUMBER = 1;
    private volatile Object deviceId_;
    /**
     * <code>string deviceId = 1;</code>
     */
    public String getDeviceId() {
      Object ref = deviceId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      }
    }
    /**
     * <code>string deviceId = 1;</code>
     */
    public com.google.protobuf.ByteString
    getDeviceIdBytes() {
      Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICEIMEI_FIELD_NUMBER = 2;
    private volatile Object deviceImei_;
    /**
     * <code>string deviceImei = 2;</code>
     */
    public String getDeviceImei() {
      Object ref = deviceImei_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        deviceImei_ = s;
        return s;
      }
    }
    /**
     * <code>string deviceImei = 2;</code>
     */
    public com.google.protobuf.ByteString
    getDeviceImeiBytes() {
      Object ref = deviceImei_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceImei_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCALTIME_FIELD_NUMBER = 3;
    private volatile Object localTime_;
    /**
     * <code>string localTime = 3;</code>
     */
    public String getLocalTime() {
      Object ref = localTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        localTime_ = s;
        return s;
      }
    }
    /**
     * <code>string localTime = 3;</code>
     */
    public com.google.protobuf.ByteString
    getLocalTimeBytes() {
      Object ref = localTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        localTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRIPID_FIELD_NUMBER = 4;
    private volatile Object tripId_;
    /**
     * <code>string tripId = 4;</code>
     */
    public String getTripId() {
      Object ref = tripId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tripId_ = s;
        return s;
      }
    }
    /**
     * <code>string tripId = 4;</code>
     */
    public com.google.protobuf.ByteString
    getTripIdBytes() {
      Object ref = tripId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tripId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVERTIME_FIELD_NUMBER = 5;
    private volatile Object serverTime_;
    /**
     * <code>string serverTime = 5;</code>
     */
    public String getServerTime() {
      Object ref = serverTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serverTime_ = s;
        return s;
      }
    }
    /**
     * <code>string serverTime = 5;</code>
     */
    public com.google.protobuf.ByteString
    getServerTimeBytes() {
      Object ref = serverTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serverTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAT_FIELD_NUMBER = 6;
    private double lat_;
    /**
     * <code>double lat = 6;</code>
     */
    public double getLat() {
      return lat_;
    }

    public static final int LONGI_FIELD_NUMBER = 7;
    private double longi_;
    /**
     * <code>double longi = 7;</code>
     */
    public double getLongi() {
      return longi_;
    }

    public static final int ALT_FIELD_NUMBER = 8;
    private double alt_;
    /**
     * <code>double alt = 8;</code>
     */
    public double getAlt() {
      return alt_;
    }

    public static final int DIR_FIELD_NUMBER = 9;
    private double dir_;
    /**
     * <code>double dir = 9;</code>
     */
    public double getDir() {
      return dir_;
    }

    public static final int GPSSPEED_FIELD_NUMBER = 10;
    private double gpsSpeed_;
    /**
     * <code>double gpsSpeed = 10;</code>
     */
    public double getGpsSpeed() {
      return gpsSpeed_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
        throws java.io.IOException {
      if (!getDeviceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, deviceId_);
      }
      if (!getDeviceImeiBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deviceImei_);
      }
      if (!getLocalTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, localTime_);
      }
      if (!getTripIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, tripId_);
      }
      if (!getServerTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, serverTime_);
      }
      if (lat_ != 0D) {
        output.writeDouble(6, lat_);
      }
      if (longi_ != 0D) {
        output.writeDouble(7, longi_);
      }
      if (alt_ != 0D) {
        output.writeDouble(8, alt_);
      }
      if (dir_ != 0D) {
        output.writeDouble(9, dir_);
      }
      if (gpsSpeed_ != 0D) {
        output.writeDouble(10, gpsSpeed_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDeviceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, deviceId_);
      }
      if (!getDeviceImeiBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deviceImei_);
      }
      if (!getLocalTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, localTime_);
      }
      if (!getTripIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, tripId_);
      }
      if (!getServerTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, serverTime_);
      }
      if (lat_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(6, lat_);
      }
      if (longi_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(7, longi_);
      }
      if (alt_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(8, alt_);
      }
      if (dir_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(9, dir_);
      }
      if (gpsSpeed_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(10, gpsSpeed_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
        return true;
      }
      if (!(obj instanceof FrequencyGps)) {
        return super.equals(obj);
      }
      FrequencyGps other = (FrequencyGps) obj;

      boolean result = true;
      result = result && getDeviceId()
          .equals(other.getDeviceId());
      result = result && getDeviceImei()
          .equals(other.getDeviceImei());
      result = result && getLocalTime()
          .equals(other.getLocalTime());
      result = result && getTripId()
          .equals(other.getTripId());
      result = result && getServerTime()
          .equals(other.getServerTime());
      result = result && (
          Double.doubleToLongBits(getLat())
              == Double.doubleToLongBits(
              other.getLat()));
      result = result && (
          Double.doubleToLongBits(getLongi())
              == Double.doubleToLongBits(
              other.getLongi()));
      result = result && (
          Double.doubleToLongBits(getAlt())
              == Double.doubleToLongBits(
              other.getAlt()));
      result = result && (
          Double.doubleToLongBits(getDir())
              == Double.doubleToLongBits(
              other.getDir()));
      result = result && (
          Double.doubleToLongBits(getGpsSpeed())
              == Double.doubleToLongBits(
              other.getGpsSpeed()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceId().hashCode();
      hash = (37 * hash) + DEVICEIMEI_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceImei().hashCode();
      hash = (37 * hash) + LOCALTIME_FIELD_NUMBER;
      hash = (53 * hash) + getLocalTime().hashCode();
      hash = (37 * hash) + TRIPID_FIELD_NUMBER;
      hash = (53 * hash) + getTripId().hashCode();
      hash = (37 * hash) + SERVERTIME_FIELD_NUMBER;
      hash = (53 * hash) + getServerTime().hashCode();
      hash = (37 * hash) + LAT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getLat()));
      hash = (37 * hash) + LONGI_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getLongi()));
      hash = (37 * hash) + ALT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getAlt()));
      hash = (37 * hash) + DIR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getDir()));
      hash = (37 * hash) + GPSSPEED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getGpsSpeed()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static FrequencyGps parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FrequencyGps parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FrequencyGps parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FrequencyGps parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static FrequencyGps parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static FrequencyGps parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FrequencyGps parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static FrequencyGps parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static FrequencyGps parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static FrequencyGps parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static FrequencyGps parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(FrequencyGps prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FrequencyGps}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FrequencyGps)
        FrequencyGpsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
        return FrequencyGpsData.internal_static_FrequencyGps_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
        return FrequencyGpsData.internal_static_FrequencyGps_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                FrequencyGps.class, Builder.class);
      }

      // Construct using com.chedaojunan.report.model.FrequencyGpsData.FrequencyGps.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
            .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        deviceId_ = "";

        deviceImei_ = "";

        localTime_ = "";

        tripId_ = "";

        serverTime_ = "";

        lat_ = 0D;

        longi_ = 0D;

        alt_ = 0D;

        dir_ = 0D;

        gpsSpeed_ = 0D;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
      getDescriptorForType() {
        return FrequencyGpsData.internal_static_FrequencyGps_descriptor;
      }

      @Override
      public FrequencyGps getDefaultInstanceForType() {
        return FrequencyGps.getDefaultInstance();
      }

      @Override
      public FrequencyGps build() {
        FrequencyGps result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public FrequencyGps buildPartial() {
        FrequencyGps result = new FrequencyGps(this);
        result.deviceId_ = deviceId_;
        result.deviceImei_ = deviceImei_;
        result.localTime_ = localTime_;
        result.tripId_ = tripId_;
        result.serverTime_ = serverTime_;
        result.lat_ = lat_;
        result.longi_ = longi_;
        result.alt_ = alt_;
        result.dir_ = dir_;
        result.gpsSpeed_ = gpsSpeed_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof FrequencyGps) {
          return mergeFrom((FrequencyGps)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(FrequencyGps other) {
        if (other == FrequencyGps.getDefaultInstance()) return this;
        if (!other.getDeviceId().isEmpty()) {
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (!other.getDeviceImei().isEmpty()) {
          deviceImei_ = other.deviceImei_;
          onChanged();
        }
        if (!other.getLocalTime().isEmpty()) {
          localTime_ = other.localTime_;
          onChanged();
        }
        if (!other.getTripId().isEmpty()) {
          tripId_ = other.tripId_;
          onChanged();
        }
        if (!other.getServerTime().isEmpty()) {
          serverTime_ = other.serverTime_;
          onChanged();
        }
        if (other.getLat() != 0D) {
          setLat(other.getLat());
        }
        if (other.getLongi() != 0D) {
          setLongi(other.getLongi());
        }
        if (other.getAlt() != 0D) {
          setAlt(other.getAlt());
        }
        if (other.getDir() != 0D) {
          setDir(other.getDir());
        }
        if (other.getGpsSpeed() != 0D) {
          setGpsSpeed(other.getGpsSpeed());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        FrequencyGps parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (FrequencyGps) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object deviceId_ = "";
      /**
       * <code>string deviceId = 1;</code>
       */
      public String getDeviceId() {
        Object ref = deviceId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string deviceId = 1;</code>
       */
      public com.google.protobuf.ByteString
      getDeviceIdBytes() {
        Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string deviceId = 1;</code>
       */
      public Builder setDeviceId(
          String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string deviceId = 1;</code>
       */
      public Builder clearDeviceId() {

        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>string deviceId = 1;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        deviceId_ = value;
        onChanged();
        return this;
      }

      private Object deviceImei_ = "";
      /**
       * <code>string deviceImei = 2;</code>
       */
      public String getDeviceImei() {
        Object ref = deviceImei_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          deviceImei_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string deviceImei = 2;</code>
       */
      public com.google.protobuf.ByteString
      getDeviceImeiBytes() {
        Object ref = deviceImei_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceImei_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string deviceImei = 2;</code>
       */
      public Builder setDeviceImei(
          String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        deviceImei_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string deviceImei = 2;</code>
       */
      public Builder clearDeviceImei() {

        deviceImei_ = getDefaultInstance().getDeviceImei();
        onChanged();
        return this;
      }
      /**
       * <code>string deviceImei = 2;</code>
       */
      public Builder setDeviceImeiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        deviceImei_ = value;
        onChanged();
        return this;
      }

      private Object localTime_ = "";
      /**
       * <code>string localTime = 3;</code>
       */
      public String getLocalTime() {
        Object ref = localTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          localTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string localTime = 3;</code>
       */
      public com.google.protobuf.ByteString
      getLocalTimeBytes() {
        Object ref = localTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          localTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string localTime = 3;</code>
       */
      public Builder setLocalTime(
          String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        localTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string localTime = 3;</code>
       */
      public Builder clearLocalTime() {

        localTime_ = getDefaultInstance().getLocalTime();
        onChanged();
        return this;
      }
      /**
       * <code>string localTime = 3;</code>
       */
      public Builder setLocalTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        localTime_ = value;
        onChanged();
        return this;
      }

      private Object tripId_ = "";
      /**
       * <code>string tripId = 4;</code>
       */
      public String getTripId() {
        Object ref = tripId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          tripId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string tripId = 4;</code>
       */
      public com.google.protobuf.ByteString
      getTripIdBytes() {
        Object ref = tripId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          tripId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tripId = 4;</code>
       */
      public Builder setTripId(
          String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        tripId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tripId = 4;</code>
       */
      public Builder clearTripId() {

        tripId_ = getDefaultInstance().getTripId();
        onChanged();
        return this;
      }
      /**
       * <code>string tripId = 4;</code>
       */
      public Builder setTripIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        tripId_ = value;
        onChanged();
        return this;
      }

      private Object serverTime_ = "";
      /**
       * <code>string serverTime = 5;</code>
       */
      public String getServerTime() {
        Object ref = serverTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          serverTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string serverTime = 5;</code>
       */
      public com.google.protobuf.ByteString
      getServerTimeBytes() {
        Object ref = serverTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serverTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string serverTime = 5;</code>
       */
      public Builder setServerTime(
          String value) {
        if (value == null) {
          throw new NullPointerException();
        }

        serverTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string serverTime = 5;</code>
       */
      public Builder clearServerTime() {

        serverTime_ = getDefaultInstance().getServerTime();
        onChanged();
        return this;
      }
      /**
       * <code>string serverTime = 5;</code>
       */
      public Builder setServerTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
          throw new NullPointerException();
        }
        checkByteStringIsUtf8(value);

        serverTime_ = value;
        onChanged();
        return this;
      }

      private double lat_ ;
      /**
       * <code>double lat = 6;</code>
       */
      public double getLat() {
        return lat_;
      }
      /**
       * <code>double lat = 6;</code>
       */
      public Builder setLat(double value) {

        lat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double lat = 6;</code>
       */
      public Builder clearLat() {

        lat_ = 0D;
        onChanged();
        return this;
      }

      private double longi_ ;
      /**
       * <code>double longi = 7;</code>
       */
      public double getLongi() {
        return longi_;
      }
      /**
       * <code>double longi = 7;</code>
       */
      public Builder setLongi(double value) {

        longi_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double longi = 7;</code>
       */
      public Builder clearLongi() {

        longi_ = 0D;
        onChanged();
        return this;
      }

      private double alt_ ;
      /**
       * <code>double alt = 8;</code>
       */
      public double getAlt() {
        return alt_;
      }
      /**
       * <code>double alt = 8;</code>
       */
      public Builder setAlt(double value) {

        alt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double alt = 8;</code>
       */
      public Builder clearAlt() {

        alt_ = 0D;
        onChanged();
        return this;
      }

      private double dir_ ;
      /**
       * <code>double dir = 9;</code>
       */
      public double getDir() {
        return dir_;
      }
      /**
       * <code>double dir = 9;</code>
       */
      public Builder setDir(double value) {

        dir_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double dir = 9;</code>
       */
      public Builder clearDir() {

        dir_ = 0D;
        onChanged();
        return this;
      }

      private double gpsSpeed_ ;
      /**
       * <code>double gpsSpeed = 10;</code>
       */
      public double getGpsSpeed() {
        return gpsSpeed_;
      }
      /**
       * <code>double gpsSpeed = 10;</code>
       */
      public Builder setGpsSpeed(double value) {

        gpsSpeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double gpsSpeed = 10;</code>
       */
      public Builder clearGpsSpeed() {

        gpsSpeed_ = 0D;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FrequencyGps)
    }

    // @@protoc_insertion_point(class_scope:FrequencyGps)
    private static final FrequencyGps DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new FrequencyGps();
    }

    public static FrequencyGps getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FrequencyGps>
        PARSER = new com.google.protobuf.AbstractParser<FrequencyGps>() {
      @Override
      public FrequencyGps parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FrequencyGps(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FrequencyGps> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<FrequencyGps> getParserForType() {
      return PARSER;
    }

    @Override
    public FrequencyGps getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
      internal_static_FrequencyGps_descriptor;
  private static final
  com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FrequencyGps_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
  getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
        "\n\020sample_gps.proto\"\263\001\n\014FrequencyGps\022\020\n\010d" +
            "eviceId\030\001 \001(\t\022\022\n\ndeviceImei\030\002 \001(\t\022\021\n\tloc" +
            "alTime\030\003 \001(\t\022\016\n\006tripId\030\004 \001(\t\022\022\n\nserverTi" +
            "me\030\005 \001(\t\022\013\n\003lat\030\006 \001(\001\022\r\n\005longi\030\007 \001(\001\022\013\n\003" +
            "alt\030\010 \001(\001\022\013\n\003dir\030\t \001(\001\022\020\n\010gpsSpeed\030\n \001(\001" +
            "B0\n\034com.chedaojunan.report.modelB\020Freque" +
            "ncyGpsDatab\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
        .internalBuildGeneratedFileFrom(descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
            }, assigner);
    internal_static_FrequencyGps_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_FrequencyGps_fieldAccessorTable = new
        com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FrequencyGps_descriptor,
        new String[] { "DeviceId", "DeviceImei", "LocalTime", "TripId", "ServerTime", "Lat", "Longi", "Alt", "Dir", "GpsSpeed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}