// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample_gps_all.proto

package com.chedaojunan.report.model;

public final class GpsData {
  private GpsData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GpsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Gps)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string deviceId = 1;</code>
     */
    String getDeviceId();
    /**
     * <code>string deviceId = 1;</code>
     */
    com.google.protobuf.ByteString
        getDeviceIdBytes();

    /**
     * <code>string deviceImei = 2;</code>
     */
    String getDeviceImei();
    /**
     * <code>string deviceImei = 2;</code>
     */
    com.google.protobuf.ByteString
        getDeviceImeiBytes();

    /**
     * <code>string localTime = 3;</code>
     */
    String getLocalTime();
    /**
     * <code>string localTime = 3;</code>
     */
    com.google.protobuf.ByteString
        getLocalTimeBytes();

    /**
     * <code>string tripId = 4;</code>
     */
    String getTripId();
    /**
     * <code>string tripId = 4;</code>
     */
    com.google.protobuf.ByteString
        getTripIdBytes();

    /**
     * <code>string serverTime = 5;</code>
     */
    String getServerTime();
    /**
     * <code>string serverTime = 5;</code>
     */
    com.google.protobuf.ByteString
        getServerTimeBytes();

    /**
     * <code>double latitude = 6;</code>
     */
    double getLatitude();

    /**
     * <code>double longitude = 7;</code>
     */
    double getLongitude();

    /**
     * <code>double altitude = 8;</code>
     */
    double getAltitude();

    /**
     * <code>double direction = 9;</code>
     */
    double getDirection();

    /**
     * <code>double gpsSpeed = 10;</code>
     */
    double getGpsSpeed();
  }
  /**
   * Protobuf type {@code Gps}
   */
  public  static final class Gps extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Gps)
      GpsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Gps.newBuilder() to construct.
    private Gps(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Gps() {
      deviceId_ = "";
      deviceImei_ = "";
      localTime_ = "";
      tripId_ = "";
      serverTime_ = "";
      latitude_ = 0D;
      longitude_ = 0D;
      altitude_ = 0D;
      direction_ = 0D;
      gpsSpeed_ = 0D;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Gps(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              deviceId_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              deviceImei_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              localTime_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              tripId_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              serverTime_ = s;
              break;
            }
            case 49: {

              latitude_ = input.readDouble();
              break;
            }
            case 57: {

              longitude_ = input.readDouble();
              break;
            }
            case 65: {

              altitude_ = input.readDouble();
              break;
            }
            case 73: {

              direction_ = input.readDouble();
              break;
            }
            case 81: {

              gpsSpeed_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GpsData.internal_static_Gps_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GpsData.internal_static_Gps_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Gps.class, Builder.class);
    }

    public static final int DEVICEID_FIELD_NUMBER = 1;
    private volatile Object deviceId_;
    /**
     * <code>string deviceId = 1;</code>
     */
    public String getDeviceId() {
      Object ref = deviceId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        deviceId_ = s;
        return s;
      }
    }
    /**
     * <code>string deviceId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceIdBytes() {
      Object ref = deviceId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVICEIMEI_FIELD_NUMBER = 2;
    private volatile Object deviceImei_;
    /**
     * <code>string deviceImei = 2;</code>
     */
    public String getDeviceImei() {
      Object ref = deviceImei_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        deviceImei_ = s;
        return s;
      }
    }
    /**
     * <code>string deviceImei = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDeviceImeiBytes() {
      Object ref = deviceImei_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        deviceImei_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LOCALTIME_FIELD_NUMBER = 3;
    private volatile Object localTime_;
    /**
     * <code>string localTime = 3;</code>
     */
    public String getLocalTime() {
      Object ref = localTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        localTime_ = s;
        return s;
      }
    }
    /**
     * <code>string localTime = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLocalTimeBytes() {
      Object ref = localTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        localTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRIPID_FIELD_NUMBER = 4;
    private volatile Object tripId_;
    /**
     * <code>string tripId = 4;</code>
     */
    public String getTripId() {
      Object ref = tripId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        tripId_ = s;
        return s;
      }
    }
    /**
     * <code>string tripId = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTripIdBytes() {
      Object ref = tripId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        tripId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVERTIME_FIELD_NUMBER = 5;
    private volatile Object serverTime_;
    /**
     * <code>string serverTime = 5;</code>
     */
    public String getServerTime() {
      Object ref = serverTime_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        serverTime_ = s;
        return s;
      }
    }
    /**
     * <code>string serverTime = 5;</code>
     */
    public com.google.protobuf.ByteString
        getServerTimeBytes() {
      Object ref = serverTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        serverTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LATITUDE_FIELD_NUMBER = 6;
    private double latitude_;
    /**
     * <code>double latitude = 6;</code>
     */
    public double getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 7;
    private double longitude_;
    /**
     * <code>double longitude = 7;</code>
     */
    public double getLongitude() {
      return longitude_;
    }

    public static final int ALTITUDE_FIELD_NUMBER = 8;
    private double altitude_;
    /**
     * <code>double altitude = 8;</code>
     */
    public double getAltitude() {
      return altitude_;
    }

    public static final int DIRECTION_FIELD_NUMBER = 9;
    private double direction_;
    /**
     * <code>double direction = 9;</code>
     */
    public double getDirection() {
      return direction_;
    }

    public static final int GPSSPEED_FIELD_NUMBER = 10;
    private double gpsSpeed_;
    /**
     * <code>double gpsSpeed = 10;</code>
     */
    public double getGpsSpeed() {
      return gpsSpeed_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDeviceIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, deviceId_);
      }
      if (!getDeviceImeiBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, deviceImei_);
      }
      if (!getLocalTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, localTime_);
      }
      if (!getTripIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, tripId_);
      }
      if (!getServerTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, serverTime_);
      }
      if (latitude_ != 0D) {
        output.writeDouble(6, latitude_);
      }
      if (longitude_ != 0D) {
        output.writeDouble(7, longitude_);
      }
      if (altitude_ != 0D) {
        output.writeDouble(8, altitude_);
      }
      if (direction_ != 0D) {
        output.writeDouble(9, direction_);
      }
      if (gpsSpeed_ != 0D) {
        output.writeDouble(10, gpsSpeed_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDeviceIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, deviceId_);
      }
      if (!getDeviceImeiBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, deviceImei_);
      }
      if (!getLocalTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, localTime_);
      }
      if (!getTripIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, tripId_);
      }
      if (!getServerTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, serverTime_);
      }
      if (latitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, latitude_);
      }
      if (longitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, longitude_);
      }
      if (altitude_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(8, altitude_);
      }
      if (direction_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(9, direction_);
      }
      if (gpsSpeed_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(10, gpsSpeed_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Gps)) {
        return super.equals(obj);
      }
      Gps other = (Gps) obj;

      boolean result = true;
      result = result && getDeviceId()
          .equals(other.getDeviceId());
      result = result && getDeviceImei()
          .equals(other.getDeviceImei());
      result = result && getLocalTime()
          .equals(other.getLocalTime());
      result = result && getTripId()
          .equals(other.getTripId());
      result = result && getServerTime()
          .equals(other.getServerTime());
      result = result && (
          Double.doubleToLongBits(getLatitude())
          == Double.doubleToLongBits(
              other.getLatitude()));
      result = result && (
          Double.doubleToLongBits(getLongitude())
          == Double.doubleToLongBits(
              other.getLongitude()));
      result = result && (
          Double.doubleToLongBits(getAltitude())
          == Double.doubleToLongBits(
              other.getAltitude()));
      result = result && (
          Double.doubleToLongBits(getDirection())
          == Double.doubleToLongBits(
              other.getDirection()));
      result = result && (
          Double.doubleToLongBits(getGpsSpeed())
          == Double.doubleToLongBits(
              other.getGpsSpeed()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICEID_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceId().hashCode();
      hash = (37 * hash) + DEVICEIMEI_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceImei().hashCode();
      hash = (37 * hash) + LOCALTIME_FIELD_NUMBER;
      hash = (53 * hash) + getLocalTime().hashCode();
      hash = (37 * hash) + TRIPID_FIELD_NUMBER;
      hash = (53 * hash) + getTripId().hashCode();
      hash = (37 * hash) + SERVERTIME_FIELD_NUMBER;
      hash = (53 * hash) + getServerTime().hashCode();
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getLatitude()));
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getLongitude()));
      hash = (37 * hash) + ALTITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getAltitude()));
      hash = (37 * hash) + DIRECTION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getDirection()));
      hash = (37 * hash) + GPSSPEED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getGpsSpeed()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Gps parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Gps parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Gps parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Gps parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Gps parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Gps parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Gps parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Gps parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Gps parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Gps parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Gps parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Gps parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Gps prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Gps}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Gps)
        GpsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return GpsData.internal_static_Gps_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return GpsData.internal_static_Gps_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Gps.class, Builder.class);
      }

      // Construct using com.chedaojunan.report.model.GpsData.Gps.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        deviceId_ = "";

        deviceImei_ = "";

        localTime_ = "";

        tripId_ = "";

        serverTime_ = "";

        latitude_ = 0D;

        longitude_ = 0D;

        altitude_ = 0D;

        direction_ = 0D;

        gpsSpeed_ = 0D;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return GpsData.internal_static_Gps_descriptor;
      }

      @Override
      public Gps getDefaultInstanceForType() {
        return Gps.getDefaultInstance();
      }

      @Override
      public Gps build() {
        Gps result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Gps buildPartial() {
        Gps result = new Gps(this);
        result.deviceId_ = deviceId_;
        result.deviceImei_ = deviceImei_;
        result.localTime_ = localTime_;
        result.tripId_ = tripId_;
        result.serverTime_ = serverTime_;
        result.latitude_ = latitude_;
        result.longitude_ = longitude_;
        result.altitude_ = altitude_;
        result.direction_ = direction_;
        result.gpsSpeed_ = gpsSpeed_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Gps) {
          return mergeFrom((Gps)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Gps other) {
        if (other == Gps.getDefaultInstance()) return this;
        if (!other.getDeviceId().isEmpty()) {
          deviceId_ = other.deviceId_;
          onChanged();
        }
        if (!other.getDeviceImei().isEmpty()) {
          deviceImei_ = other.deviceImei_;
          onChanged();
        }
        if (!other.getLocalTime().isEmpty()) {
          localTime_ = other.localTime_;
          onChanged();
        }
        if (!other.getTripId().isEmpty()) {
          tripId_ = other.tripId_;
          onChanged();
        }
        if (!other.getServerTime().isEmpty()) {
          serverTime_ = other.serverTime_;
          onChanged();
        }
        if (other.getLatitude() != 0D) {
          setLatitude(other.getLatitude());
        }
        if (other.getLongitude() != 0D) {
          setLongitude(other.getLongitude());
        }
        if (other.getAltitude() != 0D) {
          setAltitude(other.getAltitude());
        }
        if (other.getDirection() != 0D) {
          setDirection(other.getDirection());
        }
        if (other.getGpsSpeed() != 0D) {
          setGpsSpeed(other.getGpsSpeed());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Gps parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Gps) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object deviceId_ = "";
      /**
       * <code>string deviceId = 1;</code>
       */
      public String getDeviceId() {
        Object ref = deviceId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          deviceId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string deviceId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceIdBytes() {
        Object ref = deviceId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string deviceId = 1;</code>
       */
      public Builder setDeviceId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string deviceId = 1;</code>
       */
      public Builder clearDeviceId() {
        
        deviceId_ = getDefaultInstance().getDeviceId();
        onChanged();
        return this;
      }
      /**
       * <code>string deviceId = 1;</code>
       */
      public Builder setDeviceIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceId_ = value;
        onChanged();
        return this;
      }

      private Object deviceImei_ = "";
      /**
       * <code>string deviceImei = 2;</code>
       */
      public String getDeviceImei() {
        Object ref = deviceImei_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          deviceImei_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string deviceImei = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDeviceImeiBytes() {
        Object ref = deviceImei_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          deviceImei_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string deviceImei = 2;</code>
       */
      public Builder setDeviceImei(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        deviceImei_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string deviceImei = 2;</code>
       */
      public Builder clearDeviceImei() {
        
        deviceImei_ = getDefaultInstance().getDeviceImei();
        onChanged();
        return this;
      }
      /**
       * <code>string deviceImei = 2;</code>
       */
      public Builder setDeviceImeiBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        deviceImei_ = value;
        onChanged();
        return this;
      }

      private Object localTime_ = "";
      /**
       * <code>string localTime = 3;</code>
       */
      public String getLocalTime() {
        Object ref = localTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          localTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string localTime = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLocalTimeBytes() {
        Object ref = localTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          localTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string localTime = 3;</code>
       */
      public Builder setLocalTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        localTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string localTime = 3;</code>
       */
      public Builder clearLocalTime() {
        
        localTime_ = getDefaultInstance().getLocalTime();
        onChanged();
        return this;
      }
      /**
       * <code>string localTime = 3;</code>
       */
      public Builder setLocalTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        localTime_ = value;
        onChanged();
        return this;
      }

      private Object tripId_ = "";
      /**
       * <code>string tripId = 4;</code>
       */
      public String getTripId() {
        Object ref = tripId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          tripId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string tripId = 4;</code>
       */
      public com.google.protobuf.ByteString
          getTripIdBytes() {
        Object ref = tripId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          tripId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string tripId = 4;</code>
       */
      public Builder setTripId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tripId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string tripId = 4;</code>
       */
      public Builder clearTripId() {
        
        tripId_ = getDefaultInstance().getTripId();
        onChanged();
        return this;
      }
      /**
       * <code>string tripId = 4;</code>
       */
      public Builder setTripIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tripId_ = value;
        onChanged();
        return this;
      }

      private Object serverTime_ = "";
      /**
       * <code>string serverTime = 5;</code>
       */
      public String getServerTime() {
        Object ref = serverTime_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          serverTime_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string serverTime = 5;</code>
       */
      public com.google.protobuf.ByteString
          getServerTimeBytes() {
        Object ref = serverTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          serverTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string serverTime = 5;</code>
       */
      public Builder setServerTime(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        serverTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string serverTime = 5;</code>
       */
      public Builder clearServerTime() {
        
        serverTime_ = getDefaultInstance().getServerTime();
        onChanged();
        return this;
      }
      /**
       * <code>string serverTime = 5;</code>
       */
      public Builder setServerTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        serverTime_ = value;
        onChanged();
        return this;
      }

      private double latitude_ ;
      /**
       * <code>double latitude = 6;</code>
       */
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>double latitude = 6;</code>
       */
      public Builder setLatitude(double value) {
        
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double latitude = 6;</code>
       */
      public Builder clearLatitude() {
        
        latitude_ = 0D;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <code>double longitude = 7;</code>
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>double longitude = 7;</code>
       */
      public Builder setLongitude(double value) {
        
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double longitude = 7;</code>
       */
      public Builder clearLongitude() {
        
        longitude_ = 0D;
        onChanged();
        return this;
      }

      private double altitude_ ;
      /**
       * <code>double altitude = 8;</code>
       */
      public double getAltitude() {
        return altitude_;
      }
      /**
       * <code>double altitude = 8;</code>
       */
      public Builder setAltitude(double value) {
        
        altitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double altitude = 8;</code>
       */
      public Builder clearAltitude() {
        
        altitude_ = 0D;
        onChanged();
        return this;
      }

      private double direction_ ;
      /**
       * <code>double direction = 9;</code>
       */
      public double getDirection() {
        return direction_;
      }
      /**
       * <code>double direction = 9;</code>
       */
      public Builder setDirection(double value) {
        
        direction_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double direction = 9;</code>
       */
      public Builder clearDirection() {
        
        direction_ = 0D;
        onChanged();
        return this;
      }

      private double gpsSpeed_ ;
      /**
       * <code>double gpsSpeed = 10;</code>
       */
      public double getGpsSpeed() {
        return gpsSpeed_;
      }
      /**
       * <code>double gpsSpeed = 10;</code>
       */
      public Builder setGpsSpeed(double value) {
        
        gpsSpeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double gpsSpeed = 10;</code>
       */
      public Builder clearGpsSpeed() {
        
        gpsSpeed_ = 0D;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Gps)
    }

    // @@protoc_insertion_point(class_scope:Gps)
    private static final Gps DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Gps();
    }

    public static Gps getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Gps>
        PARSER = new com.google.protobuf.AbstractParser<Gps>() {
      @Override
      public Gps parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Gps(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Gps> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Gps> getParserForType() {
      return PARSER;
    }

    @Override
    public Gps getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Gps_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Gps_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024sample_gps_all.proto\"\276\001\n\003Gps\022\020\n\010device" +
      "Id\030\001 \001(\t\022\022\n\ndeviceImei\030\002 \001(\t\022\021\n\tlocalTim" +
      "e\030\003 \001(\t\022\016\n\006tripId\030\004 \001(\t\022\022\n\nserverTime\030\005 " +
      "\001(\t\022\020\n\010latitude\030\006 \001(\001\022\021\n\tlongitude\030\007 \001(\001" +
      "\022\020\n\010altitude\030\010 \001(\001\022\021\n\tdirection\030\t \001(\001\022\020\n" +
      "\010gpsSpeed\030\n \001(\001B\'\n\034com.chedaojunan.repor" +
      "t.modelB\007GpsDatab\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Gps_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Gps_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Gps_descriptor,
        new String[] { "DeviceId", "DeviceImei", "LocalTime", "TripId", "ServerTime", "Latitude", "Longitude", "Altitude", "Direction", "GpsSpeed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
